#! /bin/sh

#bspc config border_width        1
bspc config window_gap          0
bspc config border_width        1
bspc config pointer_follows_focus false
bspc config top_padding 14
bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true
bspc config focus_follows_pointer true
bspc config focused_border_color        "#2E9AFE"  #"#11809E"
bspc config focused_locked_border_color "#C7B579"

bspc config active_border_color         "#004455"
bspc config active_locked_border_color  "#7E7F89"

bspc config normal_border_color         "#000000" #"#3F3E3B"
bspc config normal_locked_border_color  "#3F3E3B"

bspc config presel_border_color         "#A7BF81"
bspc config urgent_border_color         "#EFA29A"

bspc monitor -d I II III IV V VI VII VIII IX X

#bspc rule -a Gimp desktop=^8 follow=on floating=on
#bspc rule -a Chromium desktop=^2
#bspc rule -a mplayer2 floating=on
#bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

panel &
#xmobar
#trayer &
